### ISSUE TITLE
Lab1 - Ex2 - Task 2 Error

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#9]
# Module: 01
#### Step: 13

Description of issue

While running the Test-IRMConfiguration command the encryption test fails with the following error message:
![image](https://user-images.githubusercontent.com/6410720/127054784-a6c6cee2-9bd5-498e-9a30-c9e36da249a4.png)

Repro steps:

1.Verify Azure RMS and IRM is activated in your tenant by using the following cmdlet and press Enter:

Get-IRMConfiguration | fl AzureRMSLicensingEnabled

**Comment by FireyJoe** [comment]
I ran into this too, on both JoniS and the tenant administrator:

The full error is:

PS C:\Windows\system32> Test-IRMConfiguration -Sender MeganB@contoso.com


Results : Acquiring RMS Templates ...
              - PASS: RMS Templates acquired.  Templates available: Highly Confidential \ All Employees, Highly Confidential, Confidential \ All Employees, Confidential - Finance, Highly Confidential - Project - Falcon, Encrypt, Do Not
          Forward.
          Verifying encryption ...
              - FAIL: Failed to verify encryption.
          ----------------------------------------
          Microsoft.Exchange.Data.RightsManagement.RmException: Failed to get publishing license. FailureCode:UnknownFailure. Recoverable:False. ---> Microsoft.Exchange.Data.RightsManagement.RmException: Failed to fetch the adhoc
          license handle. FailureCode:UnknownFailure. Recoverable:False. ---> Microsoft.Exchange.Data.RightsManagement.RmException: Creating AdHoc License with empty recipients. FailureCode:UnknownFailure. Recoverable:False.
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.CreateAdhocLicense(IRmEncryptionContext context, Object templateIssuer, EncryptionAlgorithm algo)
             --- End of inner exception stack trace ---
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.CreateAdhocLicense(IRmEncryptionContext context, Object templateIssuer, EncryptionAlgorithm algo)
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.GetEncryptionHandle(IRmEncryptionContext context, EncryptionAlgorithm algo)
             --- End of inner exception stack trace ---
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.GetEncryptionHandle(IRmEncryptionContext context, EncryptionAlgorithm algo)
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.InternalPrepareForEncryption(IRmEncryptionContext encryptionContext)
             at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.PrepareForEncryption(IRmEncryptionContext encryptionContext, Nullable`1 timeout)
             at Microsoft.Exchange.Management.RightsManagement.RMSValidator.ValidateEncryption(Stream& encryptedStream)
          ----------------------------------------

          OVERALL RESULT: FAIL

**Comment by darklove000** [comment]
Any updates on that lab?

**Comment by bneeb** [comment]
The problem was the script here was missing part of the end.  The script that should be run is:

Test-IRMConfiguration -Sender MeganB@contoso.com -Recipient MeganB@contoso.com

The instructions for the lab here have been updated, thanks for your patience.
